const FAMILIES=["Jonesy","Adventure","Air","Aura","8-Bit","Batman","Birthday","Blinky","Boss","Burnt Peanut","Bush","Crash Bandicoot","Crown","Demon","Dream","Duck","Dumpster Dive","Earth","Fire","Fishy","Ghost","Grim","Ironmouse","Jackrabbit","John Wick","Killswitch","King","Klombo","Llama","Mega Man","Morgana","Onigiri","Overshield","Peeky Peely","Pond","Pollo","Punk","Seven","Shadow","Sonic","Spooky Dash","Storm Scout","Striker","Tails","The Deer","Vampire","Vini Jr.","Water","X-Ray","Zero Point","Peely","Pacman"];
const TIERS=["Base","Gold","Cheat Master","Loot Hacker","Bounty Hunter","Trick or Treat"];
const NEW=["Spooky Dash","Vampire","The Deer","Dumpster Dive"];
const CURRENT_SEASON="Chapter 7 Season 4";
const SEASONS=["All seasons","This season","Coming soon","Chapter 7 Season 3"];
const SEASON_3=["Batman","Water","Earth","Fire","Duck","Ghost","Dream","Demon","Punk","King","Vini Jr.","Burnt Peanut","Zero Point","Fishy","Striker","Aura","Boss","Grim","Air","Seven","Ironmouse","Pollo","Llama","Peeky Peely"];
const SEASON_4=["Jonesy","Adventure","Bush","Sonic","Tails","Shadow","8-Bit","Jackrabbit","Crown","Killswitch","Klombo","Mega Man","Overshield","X-Ray","Onigiri","Storm Scout","Blinky","Birthday","Crash Bandicoot","Pond","Morgana","Spooky Dash","Vampire","The Deer","Dumpster Dive"];
const ALIASES={"Mega Man":["ImprovedSlide","MegaMan","Mega_Man"],"8-Bit":["8Bit","8_Bit"],"Crash Bandicoot":["CrashBandicoot","Crash_Bandicoot"],"Storm Scout":["StormScout","Storm_Scout"],"Spooky Dash":["SpookyDash","Spooky_Dash"],"Dumpster Dive":["DumpsterDive","Dumpster_Dive"],"The Deer":["TheDeer","The_Deer"],"Zero Point":["ZeroPoint","Zero_Point"],"Peeky Peely":["PeekyPeely","Peeky_Peely"],"Vini Jr.":["ViniJr","Vini_Jr"],"Pacman":["Pacman","Pac_Man"]};

function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/"/g,"&quot;").replace(/'/g,"&#39;");}
function slug(v){return String(v).toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");}
function assetSlug(v){return String(v).replace(/[^A-Za-z0-9]+/g,"");}
function tierSlugs(t){return ({Gold:["Gold"],"Cheat Master":["CheatMaster","Cheat_Master"],"Loot Hacker":["LootHacker","Loot_Hacker"],"Bounty Hunter":["BountyHunter","Bounty_Hunter"],"Trick or Treat":["TrickOrTreat","Trick_or_Treat"]}[t]||[]);}
function isTracked(n,t){return FAMILIES.includes(n)&&TIERS.includes(t);}
function spriteSeason(name){if(SEASON_3.includes(name))return "Chapter 7 Season 3";if(SEASON_4.includes(name))return "Chapter 7 Season 4";return "Unknown";}
function spriteRarity(name){return (["Crown","John Wick","Mega Man","Vini Jr."].includes(name)?"Legendary":["Batman","Sonic","Tails","Crash Bandicoot","Ironmouse"].includes(name)?"Epic":"Rare");}
function variantAssetNames(name,tier){var aliases=ALIASES[name]||[assetSlug(name),slug(name).replace(/-/g,"_")],out=[];aliases.forEach(function(a){if(tier==="Base")out.push(a);else tierSlugs(tier).forEach(function(v){out.push(a+"_"+v);});});return Array.from(new Set(out));}
function imageCandidates(name,tier){var t=tier||"Base",out=[];variantAssetNames(name,t).forEach(function(a){out.push("https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_"+a+"_L.webp");out.push("https://fortnite.gg/img/x/sprites/icons/T_Icon_BR_Creature_Sprite_"+a+".webp");});if(t!=="Base")tierSlugs(t).forEach(function(v){out.push("https://api.spritetrading.com/sprites/"+slug(name)+"-"+slug(v)+".webp?w=640");});out.push("https://api.spritetrading.com/sprites/"+slug(name)+".webp?w=640");return Array.from(new Set(out));}
function swapImage(img){
  try{var box=img.closest("[data-fallbacks]"),list=JSON.parse(box.getAttribute("data-fallbacks")||"[]"),i=Number(img.getAttribute("data-fallback-index")||0)+1;
    if(i<list.length){img.setAttribute("data-fallback-index",i);img.src=list[i];return;}
    img.style.display="none";if(box)box.classList.add("missing-art");
  }catch(e){img.style.display="none";}
}
function image(name,tier,cls){
  var list=imageCandidates(name,tier||"Base");
  return '<div class="art dynamic-art '+(cls||"")+'" data-fallbacks="'+esc(JSON.stringify(list))+'"><img src="'+esc(list[0])+'" alt="'+esc(name)+" "+esc(tier||"Base")+'" loading="lazy" onerror="swapImage(this)" onload="this.classList.add(\'loaded\')"><div class="art-label">'+esc(name)+'</div></div>';
}
function layout(title,active,content){
  var nav=[["Home","index.html"],["Sprites","index-page.html"],["New","new.html"],["Trades","trades.html"],["Chat","chat.html"],["Upcoming","upcoming.html"],["Wishlist","wishlist.html"],["Community","community.html"],["Leaderboard","leaderboard.html"],["Profile","profile.html"],["Settings","settings.html"]];
  document.title=title+" · SpriteSwap";
  var app=document.getElementById("app");
  if(!app)throw new Error("SpriteSwap app root is missing");
  var links=nav.map(function(x){return '<a class="'+(x[0]===active?"active":"")+'" href="'+x[1]+'">'+x[0]+"</a>";}).join("");
  app.innerHTML='<header class="topbar"><div class="shell"><a class="brand" href="index.html"><span class="mark">S</span><span>SpriteSwap</span></a><nav class="nav">'+links+'</nav><a class="btn nav-cta" href="trades.html">Trade</a></div></header>'+content+'<footer class="footer"><div class="shell"><b>SpriteSwap</b><span>Community sprite trading hub</span><small>SpriteSwap is an unofficial fan site and is not endorsed by Epic Games. Portions of the materials used are trademarks or copyrighted works of Epic Games, Inc. All rights reserved by Epic.</small></div></footer>';
}
function pageShell(active,kicker,title,desc,content){layout(title,active,'<main><section class="hero"><div class="shell"><div class="kicker">'+kicker+'</div><h1>'+title+'</h1><p>'+desc+'</p></div></section><section class="section"><div class="shell">'+content+"</div></section></main>");}
function savedList(key){try{return JSON.parse(localStorage.getItem(key)||"[]");}catch(e){return [];}}
function saveList(key,list){localStorage.setItem(key,JSON.stringify(Array.from(new Set(list))));}
function profileData(){try{return JSON.parse(localStorage.getItem("spriteswap-profile")||"{}");}catch(e){return {};}}
function moderationData(){try{return JSON.parse(localStorage.getItem("spriteswap-moderation")||'{"warnings":0,"bannedUntil":0,"lifetime":false}');}catch(e){return {warnings:0,bannedUntil:0,lifetime:false};}}
function moderationStatus(){var m=moderationData();if(m.lifetime)return "Lifetime restriction";if(m.bannedUntil>Date.now())return "24-hour restriction";return (m.warnings||0)+"/3 warnings";}
function moderateText(text){var raw=String(text||""),t=raw.toLowerCase();var pattern=/\b(f+u+c+k+|s+h+i+t+|b+i+t+c+h|a+s+s+h+o+l+e|d+i+c+k|c+r+a+p|p+i+s+s)\b/i;if(!pattern.test(t)){var m=moderationData();if(m.lifetime||Number(m.bannedUntil||0)>Date.now())return {ok:false,reason:m.lifetime?"You are permanently banned from chat.":"You are temporarily banned from chat."};return {ok:true,text:raw};}var m=moderationData();if(m.lifetime||Number(m.bannedUntil||0)>Date.now())return {ok:false,reason:m.lifetime?"You are permanently banned from chat.":"You are temporarily banned from chat."};m.violations=Number(m.violations||0)+1;m.warnings=Number(m.warnings||0)+1;m.lastAction="blocked";m.bannedUntil=Date.now()+86400000;if(m.violations>=3){m.lifetime=true;m.bannedUntil=0;m.lastAction="lifetime-ban";}localStorage.setItem("spriteswap-moderation",JSON.stringify(m));return {ok:false,deleteAll:true,ban:true,reason:m.lifetime?"Message blocked. Your chat account is permanently banned after repeated violations.":"Message blocked. Your chat account is banned from chat for 24 hours."};}
function tradePosts(){try{return JSON.parse(localStorage.getItem("spriteswap-trade-posts")||"[]");}catch(e){return [];}}
function saveTradePosts(a){localStorage.setItem("spriteswap-trade-posts",JSON.stringify(a));window.dispatchEvent(new Event("spriteswap-posts-changed"));}
function tradeTime(t){var d=new Date(t||Date.now());return d.toLocaleString([], {month:"short",day:"numeric",hour:"numeric",minute:"2-digit"});}
function postSpriteOptions(){return FAMILIES.map(function(n){return '<option value="'+esc(n)+'">'+esc(n)+"</option>";}).join("");}
function spriteCards(names,tier){var list=names||FAMILIES,t=tier||"Base";return list.map(function(n){return '<article class="card sprite-card tier-'+slug(t)+'" data-name="'+esc(n)+'" data-tier="'+esc(t)+'">'+image(n,t)+'<div class="card-body"><div class="card-meta"><span class="badge">'+esc(t)+'</span><span class="rarity '+slug(spriteRarity(n))+'">'+esc(spriteRarity(n))+'</span></div><h3>'+esc(n)+'</h3><p>'+esc(spriteSeason(n))+' · '+CURRENT_SEASON+'</p><div class="card-actions"><button class="mini-btn" data-collection="'+esc(n)+'::'+esc(t)+'::have">Have</button><button class="mini-btn" data-collection="'+esc(n)+'::'+esc(t)+'::need">Need</button><button class="mini-btn" data-collection="'+esc(n)+'::'+esc(t)+'::mastered">Mastered</button><button class="mini-btn" data-details="'+esc(n)+'::'+esc(t)+'">Details</button></div></div></article>';}).join("");}
function allVariantCards(names){
  var list=names||FAMILIES,html="";
  list.forEach(function(n){TIERS.forEach(function(t){if(isTracked(n,t))html+=spriteCards([n],t);});});
  return html;
}
function bindSpriteActions(){document.querySelectorAll("[data-collection]").forEach(function(b){b.onclick=function(){var p=b.getAttribute("data-collection").split("::"),id=p[0]+"::"+p[1];setCollectionStatus(id,p[2]);b.textContent=p[2]==="mastered"?"Mastered":p[2]==="have"?"Have":"Need";};});document.querySelectorAll("[data-details]").forEach(function(b){b.onclick=function(){var p=b.getAttribute("data-details").split("::");showSpriteDetails(p[0],p[1]||"Base");};});}
function showSpriteDetails(name,tier){
  var modal=document.createElement("div");modal.className="modal-backdrop";
  modal.innerHTML='<div class="modal"><button class="modal-x">×</button>'+image(name,tier,"large-art")+'<div class="kicker">SPRITE DETAILS</div><h2>'+esc(name)+'</h2><p class="muted">'+esc(tier)+' · '+CURRENT_SEASON+'</p><p>Track this sprite, add it to your wishlist, mark it mastered, or use the trade board to find someone offering it.</p><div class="actions"><button class="btn primary" id="mdWish">Wishlist</button><a class="btn" href="trades.html">Find trades</a></div></div>';
  document.body.appendChild(modal);modal.querySelector(".modal-x").onclick=function(){modal.remove();};
  modal.querySelector("#mdWish").onclick=function(){var a=savedList("spriteswap-wishlist"),id=name+"::"+tier;if(!a.includes(id))a.push(id);saveList("spriteswap-wishlist",a);this.textContent="Saved";};
}
function initHome(){
  layout("Home","Home",'<main><section class="hero home-hero"><div class="shell hero-grid"><div><div class="kicker">SPRITESWAP / COMMUNITY HUB</div><h1>Trade. Collect.<br><span style="color:var(--mint)">Complete your set.</span></h1><p>Browse real sprite artwork, post trades, manage your wishlist and talk with other collectors.</p><div class="actions"><a class="btn primary" href="index-page.html">Browse sprites</a><a class="btn" href="trades.html">Find a trade</a><a class="btn" href="chat.html">Community chat</a></div></div><div class="hero-card feature-sprite"><div class="kicker">FEATURED · '+CURRENT_SEASON+'</div>'+image("Crown","Gold")+'<strong>Gold Crown</strong><p>Featured variant</p></div></div></section><section class="section"><div class="shell"><div class="section-head"><div><div class="kicker">NEW</div><h2>New this season</h2></div><a class="btn" href="new.html">View all</a></div><div class="grid">'+spriteCards(NEW,"Base")+'</div></div></section><section class="section"><div class="shell"><div class="section-head"><div><div class="kicker">TRADE BOARD</div><h2>Fresh activity</h2></div><a class="btn" href="trades.html">Open board</a></div><div class="list"><div class="row"><div class="avatar">P</div><div class="grow"><b>Pacman</b><div class="muted">New sprite watch</div></div></div><div class="row"><div class="avatar">T</div><div class="grow"><b>Trade smarter</b><div class="muted">Open a listing, inspect it, then accept to start a private trade chat.</div></div></div></div></div></section></main>');
  bindSpriteActions();
}
function collectionStatus(id){var m=savedList("spriteswap-mastered"),h=savedList("spriteswap-have"),n=savedList("spriteswap-need");return m.includes(id)?"mastered":h.includes(id)?"have":n.includes(id)?"need":"missing";}
function setCollectionStatus(id,status){["spriteswap-have","spriteswap-need","spriteswap-mastered"].forEach(function(k){saveList(k,savedList(k).filter(function(x){return x!==id;}));});if(status!=="missing"){var k=status==="have"?"spriteswap-have":status==="need"?"spriteswap-need":"spriteswap-mastered",a=savedList(k);if(!a.includes(id))a.push(id);saveList(k,a);}}
function spriteLevel(id){try{return Number(JSON.parse(localStorage.getItem("spriteswap-levels")||"{}")[id]||1);}catch(e){return 1;}}
function initIndex(){
  layout("Sprite Index","Sprites",'<main><section class="hero"><div class="shell hero-grid"><div><div class="kicker">SPRITESWAP / INDEX</div><h1>Build your collection.<br><span style="color:var(--mint)">Your way.</span></h1><p>Filter by season, variant, collection state, level and rarity.</p></div><div class="hero-card"><div class="kicker">MY COLLECTION</div><strong id="collectionSummary">0</strong><p>marked entries</p></div></div></section><section class="section"><div class="shell"><div class="tools sprite-tools"><input id="search" class="input" placeholder="Search sprites…"><select id="season" class="select"><option>All seasons</option>'+SEASONS.slice(1).map(function(s){return "<option>"+esc(s)+"</option>";}).join("")+'</select><select id="tier" class="select"><option value="all">Any variant</option>'+TIERS.map(function(t){return "<option>"+esc(t)+"</option>";}).join("")+'</select><select id="collection" class="select"><option value="all">My Collection · All</option><option value="have">Have</option><option value="need">Need</option><option value="mastered">Mastered</option><option value="missing">Not marked</option></select><select id="level" class="select"><option value="all">Any level</option><option value="2">Level 2+</option><option value="3">Level 3+</option><option value="4">Level 4+</option><option value="5">Level 5</option></select><select id="rarity" class="select"><option value="all">Any rarity</option><option>Rare</option><option>Epic</option><option>Legendary</option></select><select id="sort" class="select"><option value="name">Name A–Z</option><option value="new">Newest first</option><option value="rarity">Rarity</option></select></div><div class="index-viewbar"><span id="resultCount"></span><button id="resetIndex" class="btn">Reset filters</button></div><div id="grid" class="grid"></div></div></section></main>');
  function render(){
    var q=document.getElementById("search").value.toLowerCase().trim(),s=document.getElementById("season").value,t=document.getElementById("tier").value,st=document.getElementById("collection").value,l=document.getElementById("level").value,r=document.getElementById("rarity").value,sort=document.getElementById("sort").value;
    var n=FAMILIES.filter(function(x){var id=x+"::"+(t==="all"?"Base":t);return x.toLowerCase().includes(q)&&(s==="All seasons"||(s==="This season"&&spriteSeason(x)===CURRENT_SEASON)||(s==="Coming soon"&&NEW.includes(x))||spriteSeason(x)===s)&&(r==="all"||spriteRarity(x)===r)&&(st==="all"||collectionStatus(id)===st)&&(l==="all"||spriteLevel(id)>=Number(l));});
    if(sort==="new")n.sort(function(a,b){return Number(NEW.includes(b))-Number(NEW.includes(a))||a.localeCompare(b);});else if(sort==="rarity"){var rr={Legendary:0,Epic:1,Rare:2};n.sort(function(a,b){return rr[spriteRarity(a)]-rr[spriteRarity(b)]||a.localeCompare(b);});}else n.sort(function(a,b){return a.localeCompare(b);});
    var html="";n.forEach(function(name){TIERS.forEach(function(tier){if(t==="all"||tier===t)html+=spriteCards([name],tier);});});
    document.getElementById("grid").innerHTML=html||'<div class="notice">No sprites match those filters.</div>';
    document.getElementById("resultCount").textContent=n.length+" families · "+(html?document.querySelectorAll("#grid .sprite-card").length:0)+" cards";
    document.getElementById("collectionSummary").textContent=savedList("spriteswap-have").length+savedList("spriteswap-need").length+savedList("spriteswap-mastered").length;
    bindSpriteActions();
  }
  ["search","season","tier","collection","level","rarity","sort"].forEach(function(id){document.getElementById(id).oninput=render;document.getElementById(id).onchange=render;});
  document.getElementById("resetIndex").onclick=function(){document.getElementById("search").value="";document.getElementById("season").value="All seasons";["tier","collection","level","rarity"].forEach(function(id){document.getElementById(id).value="all";});document.getElementById("sort").value="name";render();};
  render();
}
function initNew(){pageShell("New","LATEST","New sprites","The newest sprite families currently tracked by SpriteSwap.",'<div class="grid">'+spriteCards(NEW,"Base")+"</div>");bindSpriteActions();}
function renderPostCard(x){
  var get=x.get||[],give=x.give||[];
  var chips=function(a){return a.map(function(s){return '<span class="trade-chip">'+esc(s.name||s)+' · '+esc(s.tier||"Base")+"</span>";}).join("");};
  return '<article class="trade-post" data-post-view="'+esc(x.id)+'"><div class="trade-post-top"><div><span class="badge">OPEN</span><h3>'+esc(x.title||"Sprite trade")+'</h3><p class="muted">'+esc(x.trader||"SpriteSwap Trader")+' · '+tradeTime(x.createdAt)+'</p></div><button class="btn primary" data-post-view="'+esc(x.id)+'">View trade</button></div><div class="post-columns"><div><div class="post-side-title get">YOU GET</div><div>'+chips(get)+'</div></div><div><div class="post-side-title give">YOU GIVE</div><div>'+chips(give)+'</div></div></div><p class="muted">'+esc(x.note||"Open to fair offers.")+'</p></article>';
}
function openTradePostModal(existing){
  var modal=document.createElement("div");modal.className="modal-backdrop";
  var p=existing||{};
  var row=function(side){return '<div class="picker-row"><select class="select pick-name" data-side="'+side+'">'+postSpriteOptions()+'</select><select class="select pick-tier" data-side="'+side+'">'+TIERS.map(function(t){return "<option>"+esc(t)+"</option>";}).join("")+'</select><button class="mini-btn remove-pick" type="button">×</button></div>';};
  modal.innerHTML='<div class="modal wide-modal"><button class="modal-x">×</button><div class="kicker">TRADE POST</div><h2>'+esc(p.title||"Create a trade")+'</h2><label>Title<input id="tradeTitle" class="input" value="'+esc(p.title||"")+'" placeholder="What are you looking for?"></label><label>Note<textarea id="tradeNote" class="input" rows="3" placeholder="Add a little context…">'+esc(p.note||"")+'</textarea></label><div class="post-builder"><section><div class="post-side-title get">YOU GET</div><div id="getPickers">'+(p.get||[]).map(function(){return row("get");}).join("")+'</div><button id="addGet" class="btn" type="button">+ Add sprite</button></section><section><div class="post-side-title give">YOU GIVE</div><div id="givePickers">'+(p.give||[]).map(function(){return row("give");}).join("")+'</div><button id="addGive" class="btn" type="button">+ Add sprite</button></section></div><div class="actions"><button id="saveTrade" class="btn primary">Post trade</button></div></div>';
  document.body.appendChild(modal);
  var add=function(id,side){document.getElementById(id).insertAdjacentHTML("beforeend",row(side));};
  modal.querySelector("#addGet").onclick=function(){add("getPickers","get");};modal.querySelector("#addGive").onclick=function(){add("givePickers","give");};
  modal.addEventListener("click",function(e){if(e.target.classList.contains("remove-pick"))e.target.parentElement.remove();});
  modal.querySelector(".modal-x").onclick=function(){modal.remove();};
  modal.querySelector("#saveTrade").onclick=function(){
    var read=function(id){return Array.from(modal.querySelectorAll("#"+id+" .picker-row")).map(function(r){return {name:r.querySelector(".pick-name").value,tier:r.querySelector(".pick-tier").value};});};
    var get=read("getPickers"),give=read("givePickers");
    if(!get.length||!give.length){alert("Add at least one sprite on both sides.");return;}
    var all=tradePosts(),name=String(profileData().name||"SpriteSwap Trader"),obj=Object.assign({},p);
    obj.id=obj.id||("trade-"+Date.now()+"-"+Math.random().toString(36).slice(2,7));obj.title=document.getElementById("tradeTitle").value.trim()||"Sprite trade";obj.note=document.getElementById("tradeNote").value.trim();obj.get=get;obj.give=give;obj.trader=obj.trader||name;obj.createdAt=obj.createdAt||Date.now();obj.status="open";delete obj.acceptedBy;delete obj.acceptedAt;
    var i=all.findIndex(function(x){return x.id===obj.id;});if(i<0)all.unshift(obj);else all[i]=obj;saveTradePosts(all);modal.remove();
  };
}
function openTradeDetails(post){
  var modal=document.createElement("div");modal.className="modal-backdrop";
  var cards=function(a){return a.map(function(s){return '<div class="detail-sprite">'+image(s.name,s.tier||"Base")+'<b>'+esc(s.name)+'</b><small>'+esc(s.tier||"Base")+"</small></div>";}).join("");};
  var me=String(profileData().name||"SpriteSwap Trader"),accepted=post.status==="negotiating";
  var action=accepted?'<button id="privateTrade" class="btn primary">Open private chat</button><button id="returnTrade" class="btn danger-btn">Return to board</button>':'<button id="acceptTrade" class="btn primary">Accept trade</button>';
  modal.innerHTML='<div class="modal trade-detail-modal"><button class="modal-x">×</button><div class="kicker">TRADE DETAILS</div><h2>'+esc(post.title||"Sprite trade")+'</h2><p class="muted">Posted by '+esc(post.trader||"SpriteSwap Trader")+' · '+tradeTime(post.createdAt)+'</p><div class="trade-detail-grid"><section><div class="post-side-title get">YOU GET</div><div class="detail-sprites">'+cards(post.get||[])+'</div></section><section><div class="post-side-title give">YOU GIVE</div><div class="detail-sprites">'+cards(post.give||[])+'</div></section></div><p>'+esc(post.note||"Open to fair offers.")+'</p><div class="trade-detail-actions">'+action+'</div><div class="notice"><b>After acceptance:</b> the listing leaves the public board and a private trade chat opens. Returning the trade puts it back on the board.</div></div>';
  document.body.appendChild(modal);
  modal.querySelector(".modal-x").onclick=function(){modal.remove();};
  var accept=modal.querySelector("#acceptTrade");
  if(accept)accept.onclick=function(){var all=tradePosts(),x=all.find(function(a){return a.id===post.id;});if(!x)return;x.status="negotiating";x.acceptedBy=me;x.acceptedAt=Date.now();saveTradePosts(all);modal.remove();location.hash="trade-chat="+encodeURIComponent(x.id);};
  var open=modal.querySelector("#privateTrade");if(open)open.onclick=function(){modal.remove();location.hash="trade-chat="+encodeURIComponent(post.id);};
  var back=modal.querySelector("#returnTrade");if(back)back.onclick=function(){var all=tradePosts(),x=all.find(function(a){return a.id===post.id;});if(x){x.status="open";delete x.acceptedBy;delete x.acceptedAt;saveTradePosts(all);}modal.remove();};
}
function initTrades(){
  var render=function(){
    var search=document.getElementById("postSearch"),sideEl=document.getElementById("postSide"),tierEl=document.getElementById("postTier");
    var q=search?search.value.toLowerCase().trim():"",side=sideEl?sideEl.value:"all",tier=tierEl?tierEl.value:"all";
    var posts=tradePosts().filter(function(x){return (x.status||"open")==="open";}).filter(function(x){
      var all=[].concat(x.get||[],x.give||[]).map(function(s){return typeof s==="string"?s:s.name;}).join(" ").toLowerCase(),trader=String(x.trader||"").toLowerCase();
      var sideList=side==="get"?x.get:side==="give"?x.give:[].concat(x.get||[],x.give||[]);
      return (!q||all.includes(q)||trader.includes(q)||String(x.title||"").toLowerCase().includes(q))&&sideList.length>0&&(tier==="all"||[].concat(x.get||[],x.give||[]).some(function(s){return (s.tier||"Base")===tier;}));
    });
    layout("Trades","Trades",'<main><section class="hero trades-hero"><div class="shell"><div class="kicker">TRADING BOARD</div><h1>Find your next<br><span style="color:var(--mint)">sprite swap.</span></h1><p>Click any listing to inspect it. Accept a trade to move it into a private chat.</p><div class="actions"><button class="btn primary" id="newTradePost">+ Post a trade</button><a class="btn" href="chat.html">Community chat</a></div></div></section><section class="section"><div class="shell"><div class="post-filters"><input id="postSearch" class="input" value="'+esc(q)+'" placeholder="Search trades…"><select id="postSide" class="select"><option value="all">All posts</option><option value="get"'+(side==="get"?" selected":"")+'>Looking for something</option><option value="give"'+(side==="give"?" selected":"")+'>Offering something</option></select><select id="postTier" class="select"><option value="all">Any variant</option>'+TIERS.map(function(t){return '<option'+(tier===t?" selected":"")+'>'+esc(t)+"</option>";}).join("")+'</select><button id="clearPostFilters" class="btn">Reset</button></div><div id="tradePostList" class="trade-post-list">'+(posts.map(renderPostCard).join("")||'<div class="notice empty-posts"><b>No open trade posts.</b><span>Be the first to post one.</span></div>')+"</div></div></section></main>");
    document.getElementById("newTradePost").onclick=function(){openTradePostModal();};
    document.getElementById("postSearch").oninput=render;document.getElementById("postSide").onchange=render;document.getElementById("postTier").onchange=render;document.getElementById("clearPostFilters").onclick=function(){document.getElementById("postSearch").value="";document.getElementById("postSide").value="all";document.getElementById("postTier").value="all";render();};
    document.querySelectorAll("[data-post-view]").forEach(function(b){b.onclick=function(e){e.stopPropagation();var x=tradePosts().find(function(p){return p.id===b.getAttribute("data-post-view");});if(x)openTradeDetails(x);};});
  };
  window.addEventListener("storage",function(e){if(e.key==="spriteswap-trade-posts")render();});window.addEventListener("spriteswap-posts-changed",render);render();
}
function initChat(){
  var key="spriteswap-community-chat",read=function(){try{return JSON.parse(localStorage.getItem(key)||"[]");}catch(e){return[];}},write=function(a){localStorage.setItem(key,JSON.stringify(a.slice(-200)));};
  var render=function(){var msgs=read();layout("Chat","Chat",'<main><section class="section chat-page"><div class="shell"><div class="kicker">COMMUNITY CHAT</div><h1>Talk sprites.</h1><p class="muted">General chat for the community. Trade negotiations belong in private trade chat.</p><div class="chat-messages">'+(msgs.map(function(m){return '<div class="chat-msg"><div class="avatar">'+esc((m.name||"S")[0])+'</div><div class="chat-bubble"><b>'+esc(m.name)+'</b><div>'+esc(m.text)+'</div></div></div>';}).join("")||'<div class="notice">No messages yet.</div>')+'</div><div class="chat-compose"><input id="communityMessage" class="input" maxlength="500" placeholder="Say something…"><button id="sendCommunity" class="btn primary">Send</button></div></div></section></main>');var send=function(){var i=document.getElementById("communityMessage"),t=i.value.trim();if(!t)return;var p=profileData(),name=String(p.name||"SpriteSwap Trader"),mod=moderateText(t);if(!mod.ok){var all=read();if(mod.deleteAll){all=all.filter(function(m){return m.name!==name;});write(all);}alert(mod.reason);render();return;}var a=read();a.push({name:name,text:t,createdAt:Date.now()});write(a);render();};document.getElementById("sendCommunity").onclick=send;document.getElementById("communityMessage").onkeydown=function(e){if(e.key==="Enter")send();};};
  render();
}
function initPrivateTradeChat(){
  var id=decodeURIComponent((location.hash||"").replace("#trade-chat=","")),post=tradePosts().find(function(x){return x.id===id;});
  if(!post||post.status!=="negotiating"){location.hash="";initTrades();return;}
  var key="spriteswap-private-chat-"+id,me=String(profileData().name||"SpriteSwap Trader"),read=function(){try{return JSON.parse(localStorage.getItem(key)||"[]");}catch(e){return[];}},write=function(a){localStorage.setItem(key,JSON.stringify(a.slice(-200)));};
  var render=function(){var msgs=read();layout("Private Trade","Trades",'<main><section class="section"><div class="shell"><div class="kicker">PRIVATE TRADE</div><h1>'+esc(post.title||"Sprite trade")+'</h1><p class="muted">'+esc(post.trader)+" ↔ "+esc(post.acceptedBy||me)+'</p><div class="trade-private-summary"><div><b>You get</b><div>'+[].concat(post.get||[]).map(function(s){return '<span class="trade-chip">'+esc(s.name)+" · "+esc(s.tier||"Base")+"</span>";}).join("")+'</div></div><div><b>You give</b><div>'+[].concat(post.give||[]).map(function(s){return '<span class="trade-chip">'+esc(s.name)+" · "+esc(s.tier||"Base")+"</span>";}).join("")+'</div></div></div><div class="chat-messages trade-private-messages">'+(msgs.map(function(m){return '<div class="chat-msg"><div class="avatar">'+esc((m.name||"S")[0])+'</div><div class="chat-bubble"><b>'+esc(m.name)+'</b><div>'+esc(m.text)+'</div></div></div>';}).join("")||'<div class="notice">No private messages yet.</div>')+'</div><div class="chat-compose"><input id="privateInput" class="input" maxlength="500" placeholder="Talk about this trade…"><button id="privateSend" class="btn primary">Send</button></div><div class="actions"><a class="btn" href="trades.html">Back to board</a><button id="declinePrivate" class="btn danger-btn">Decline / return to board</button></div></div></section></main>');var send=function(){var i=document.getElementById("privateInput"),t=i.value.trim();if(!t)return;var mod=moderateText(t);if(!mod.ok){if(mod.deleteAll){write(read().filter(function(m){return m.name!==me;}));}alert(mod.reason);render();return;}var a=read();a.push({name:me,text:t,createdAt:Date.now()});write(a);render();};document.getElementById("privateSend").onclick=send;document.getElementById("privateInput").onkeydown=function(e){if(e.key==="Enter")send();};document.getElementById("declinePrivate").onclick=function(){var all=tradePosts(),x=all.find(function(a){return a.id===id;});if(x){x.status="open";delete x.acceptedBy;delete x.acceptedAt;saveTradePosts(all);}location.href="trades.html";};};
  render();
}
function initWishlist(){
  var wanted=savedList("spriteswap-wishlist"),mastered=savedList("spriteswap-mastered"),make=function(ids,label){return ids.map(function(id){var p=id.split("::");return '<article class="card sprite-card">'+image(p[0],p[1]||"Base")+'<div class="card-body"><span class="badge">'+label+'</span><h3>'+esc(p[0])+'</h3><p>'+esc(p[1]||"Base")+'</p><button class="mini-btn" data-remove="'+esc(id)+'">Remove</button></div></article>';}).join("");};
  layout("Wishlist","Wishlist",'<main><section class="hero"><div class="shell"><div class="kicker">YOUR COLLECTION</div><h1>Wishlist & Mastered</h1><p>Keep the sprites you want and the ones you have finished.</p></div></section><section class="section"><div class="shell"><h2>Wishlist</h2><div class="grid">'+(make(wanted,"WISHLIST")||'<div class="notice">Your wishlist is empty.</div>')+'</div><h2 style="margin-top:42px">Mastered</h2><div class="grid">'+(make(mastered,"MASTERED")||'<div class="notice">No mastered sprites yet.</div>')+"</div></div></section></main>");
  document.querySelectorAll("[data-remove]").forEach(function(b){b.onclick=function(){var id=b.getAttribute("data-remove");["spriteswap-wishlist","spriteswap-mastered"].forEach(function(k){saveList(k,savedList(k).filter(function(x){return x!==id;}));});initWishlist();};});
}
function initUpcoming(){pageShell("Upcoming","UP NEXT","Upcoming sprites","Watch unreleased sprites and variants. Released sprites live in New This Week.",'<div class="grid">'+[["Crown","Loot Master Crown variant"],["Spooky Dash","Halloween event watch"],["Vampire","Upcoming family"],["The Deer","Upcoming family"],["Dumpster Dive","Upcoming family"]].map(function(x){return '<article class="card sprite-card">'+image(x[0],x[0]==="Crown"?"Loot Hacker":"Base")+'<div class="card-body"><span class="badge new">UPCOMING</span><h3>'+esc(x[0])+'</h3><p>'+esc(x[1])+'</p></div></article>';}).join("")+"</div>");}
function initLeaderboard(){var mastered=savedList("spriteswap-mastered"),total=Math.max(1,TIERS.reduce(function(s,t){return s+FAMILIES.filter(function(n){return isTracked(n,t);}).length;},0));pageShell("Leaderboard","COMMUNITY","Leaderboard","Local collection progress and community placeholders.",'<div class="list"><div class="row"><div class="rank">1</div><div class="grow"><b>'+esc(profileData().name||"SpriteSwap Trader")+'</b><div class="muted">Your collection</div></div><strong>'+Math.round(mastered.length/total*100)+'%</strong></div><div class="row"><div class="rank">—</div><div class="grow"><b>Community rankings</b><div class="muted">Connect the backend later for live cross-device rankings.</div></div></div></div>');}
function initProfile(){var p=profileData(),name=String(p.name||"SpriteSwap Trader"),bio=String(p.bio||"Sprite collector and trader."),avatar=String(p.avatar||"S");layout("Profile","Profile",'<main><section class="hero"><div class="shell"><div class="profile-hero"><div class="profile-avatar">'+esc(avatar.slice(0,1))+'</div><div><div class="kicker">PROFILE</div><h1>'+esc(name)+'</h1><p>'+esc(bio)+'</p></div></div></div></section><section class="section"><div class="shell"><div class="stats"><div class="stat"><b>'+savedList("spriteswap-wishlist").length+'</b><span>Wishlist</span></div><div class="stat"><b>'+savedList("spriteswap-mastered").length+'</b><span>Mastered</span></div><div class="stat"><b>'+tradePosts().filter(function(x){return x.trader===name;}).length+'</b><span>Trade posts</span></div></div><div class="actions"><a class="btn primary" href="account.html">Edit profile</a><a class="btn" href="trades.html">View trades</a></div></div></section></main>');}
function initAccount(){var p=profileData();layout("Account","Profile",'<main><section class="section"><div class="shell"><div class="hero-card"><div class="kicker">ACCOUNT</div><h1>Your SpriteSwap identity</h1><label>Username<input id="accountName" class="input" value="'+esc(p.name||"SpriteSwap Trader")+'"></label><label>Bio<textarea id="accountBio" class="input" rows="3">'+esc(p.bio||"Sprite collector and trader.")+'</textarea></label><label>Avatar letter<input id="accountAvatar" maxlength="1" class="input" value="'+esc(p.avatar||"S")+'"></label><div class="actions"><button id="saveAccount" class="btn primary">Save profile</button></div></div></div></section></main>');document.getElementById("saveAccount").onclick=function(){localStorage.setItem("spriteswap-profile",JSON.stringify({name:document.getElementById("accountName").value.trim()||"SpriteSwap Trader",bio:document.getElementById("accountBio").value.trim(),avatar:document.getElementById("accountAvatar").value.trim().slice(0,1)||"S"}));location.href="profile.html";};}
function initSettings(){
  var themes={mint:["#07110f","#10231e","#62f5bf","#c7ff55"],blue:["#07101b","#10213a","#5bbcff","#78f0ff"],purple:["#10091a","#231535","#c68cff","#f2a8ff"],orange:["#170d07","#2b1b10","#ffb35c","#ffd166"]};
  var current=localStorage.getItem("spriteswap-theme")||"mint",reduced=localStorage.getItem("spriteswap-reduced-motion")==="1",compact=localStorage.getItem("spriteswap-compact")==="1";
  layout("Settings","Settings",'<main><section class="hero"><div class="shell"><div class="kicker">SETTINGS</div><h1>Clean controls.<br><span style="color:var(--mint)">Nothing extra.</span></h1><p>Appearance, browsing, profile and safety settings in one place.</p></div></section><section class="section"><div class="shell"><div class="settings-grid"><div class="hero-card"><h2>Appearance</h2><p class="muted">Choose the accent used around SpriteSwap.</p><div class="theme-options">'+Object.keys(themes).map(function(k){return '<button class="theme-choice '+(k===current?"selected":"")+'" data-theme="'+k+'"><i style="background:'+themes[k][2]+'"></i>'+k[0].toUpperCase()+k.slice(1)+"</button>";}).join("")+'</div><label class="setting-row"><span><b>Custom accent</b><small>Pick your own accent.</small></span><input id="customAccent" type="color" value="'+esc(localStorage.getItem("spriteswap-custom-accent")||themes[current][2])+'"></label></div><div class="hero-card"><h2>Browsing</h2><label class="setting-row"><span><b>Reduce motion</b><small>Use fewer animated effects.</small></span><input id="reduceMotion" type="checkbox" '+(reduced?"checked":"")+'></label><label class="setting-row"><span><b>Compact cards</b><small>Tighter sprite browsing.</small></span><input id="compactMode" type="checkbox" '+(compact?"checked":"")+'></label></div><div class="hero-card"><h2>Community</h2><p class="muted">Use the public chat for general conversation. Trade negotiations happen in private trade chats.</p><div class="actions"><a class="btn primary" href="chat.html">Community chat</a><a class="btn" href="report.html">Reports</a></div></div><div class="hero-card"><h2>Profile</h2><p class="muted">Manage your public SpriteSwap profile.</p><div class="actions"><a class="btn" href="profile.html">Profile</a><a class="btn" href="account.html">Account</a></div></div><div class="hero-card"><h2>Data</h2><p class="muted">Preferences stay in this browser.</p><button id="resetSettings" class="btn">Reset site settings</button></div></div></div></section></main>');
  var apply=function(k){var t=themes[k]||themes.mint;document.documentElement.style.setProperty("--bg",t[0]);document.documentElement.style.setProperty("--bg2",t[0]);document.documentElement.style.setProperty("--panel",t[1]);document.documentElement.style.setProperty("--mint",t[2]);document.documentElement.style.setProperty("--lime",t[3]);localStorage.setItem("spriteswap-theme",k);document.querySelectorAll("[data-theme]").forEach(function(b){b.classList.toggle("selected",b.getAttribute("data-theme")===k);});};
  apply(current);
  document.querySelectorAll("[data-theme]").forEach(function(b){b.onclick=function(){apply(b.getAttribute("data-theme"));};});
  document.getElementById("customAccent").oninput=function(){localStorage.setItem("spriteswap-custom-accent",this.value);document.documentElement.style.setProperty("--mint",this.value);document.documentElement.style.setProperty("--aqua",this.value);};
  document.getElementById("reduceMotion").onchange=function(){localStorage.setItem("spriteswap-reduced-motion",this.checked?"1":"0");document.documentElement.classList.toggle("reduce-motion",this.checked);};
  document.getElementById("compactMode").onchange=function(){localStorage.setItem("spriteswap-compact",this.checked?"1":"0");document.documentElement.classList.toggle("compact-mode",this.checked);};
  document.getElementById("resetSettings").onclick=function(){["spriteswap-theme","spriteswap-custom-accent","spriteswap-reduced-motion","spriteswap-compact"].forEach(function(k){localStorage.removeItem(k);});location.reload();};
}
function initCommunity(){pageShell("Community","COMMUNITY","Community","Everything you need for the SpriteSwap community in one place.",'<div class="grid"><div class="hero-card"><h2>Community chat</h2><p>Talk about sprites and trades.</p><a class="btn primary" href="chat.html">Open chat</a></div><div class="hero-card"><h2>Trade board</h2><p>Find, post and manage 48-hour trade listings.</p><a class="btn primary" href="trades.html">Open trades</a></div><div class="hero-card"><h2>My Collection</h2><p>Track Have, Need and Mastered sprites.</p><a class="btn" href="index-page.html">Open collection</a></div><div class="hero-card"><h2>Rules</h2><p>Keep trades honest and conversations respectful.</p><a class="btn" href="rules.html">Read rules</a></div><div class="hero-card"><h2>Reports</h2><p>Report a listing or site problem.</p><a class="btn" href="report.html">Report a problem</a></div><div class="hero-card"><h2>New This Week</h2><p>See released sprites separately from Upcoming.</p><a class="btn" href="new-this-week.html">Open new sprites</a></div></div>');}
function initSimple(){
  var p=location.pathname.split("/").pop()||"index.html";
  if(p==="index.html")return initHome();
  if(p==="index-page.html")return initIndex();
  if(p==="new.html")return initNew();
  if(p==="trades.html"){if((location.hash||"").indexOf("#trade-chat=")===0)return initPrivateTradeChat();return initTrades();}
  if(p==="chat.html")return initChat();
  if(p==="settings.html")return initSettings();
  if(p==="upcoming.html")return initUpcoming();
  if(p==="leaderboard.html")return initLeaderboard();
  if(p==="wishlist.html")return initWishlist();
  if(p==="profile.html")return initProfile();
  if(p==="account.html")return initAccount();
  if(p==="community.html")return initCommunity();
  if(p==="report.html")return pageShell("Report","SAFETY","Report a problem","Use this page to flag a listing or site issue.",'<div class="hero-card"><textarea id="reportText" class="input" rows="7" placeholder="Describe the problem…"></textarea><div class="actions"><button class="btn primary" onclick="alert(\'Thanks — your report was recorded locally for this demo.\')">Submit report</button></div></div>');
  if(p==="rules.html")return pageShell("Rules","COMMUNITY","Community rules","Keep SpriteSwap friendly and useful.",'<div class="list"><div class="row"><div class="rank">1</div><div>Be respectful.</div></div><div class="row"><div class="rank">2</div><div>No fake trades or scams.</div></div><div class="row"><div class="rank">3</div><div>Do not spam listings.</div></div><div class="row"><div class="rank">4</div><div>Use reports for problems.</div></div></div>');
  return initHome();
}
function applyStoredSettings(){
  var themes={mint:["#07110f","#10231e","#62f5bf","#c7ff55"],blue:["#07101b","#10213a","#5bbcff","#78f0ff"],purple:["#10091a","#231535","#c68cff","#f2a8ff"],orange:["#170d07","#2b1b10","#ffb35c","#ffd166"]};
  var k=localStorage.getItem("spriteswap-theme")||"mint",t=themes[k]||themes.mint,custom=localStorage.getItem("spriteswap-custom-accent");
  document.documentElement.style.setProperty("--bg",t[0]);document.documentElement.style.setProperty("--bg2",t[0]);document.documentElement.style.setProperty("--panel",t[1]);document.documentElement.style.setProperty("--mint",custom||t[2]);document.documentElement.style.setProperty("--lime",t[3]);document.documentElement.style.setProperty("--aqua",custom||t[2]);
  document.documentElement.classList.toggle("reduce-motion",localStorage.getItem("spriteswap-reduced-motion")==="1");document.documentElement.classList.toggle("compact-mode",localStorage.getItem("spriteswap-compact")==="1");
}
function safeStart(){
  try{applyStoredSettings();initSimple();}
  catch(err){
    console.error("SpriteSwap startup error:",err);
    var app=document.getElementById("app");
    if(app)app.innerHTML='<main class="section"><div class="shell"><div class="hero-card"><div class="kicker">SPRITESWAP</div><h1>SpriteSwap hit a startup error.</h1><p class="muted">The old loading screen has been removed. This message shows the actual error instead of leaving the site stuck.</p><pre style="white-space:pre-wrap;overflow:auto;padding:12px;border-radius:10px;background:rgba(0,0,0,.25)">'+esc(err&&err.stack||err&&err.message||err)+'</pre><div class="actions"><button class="btn primary" onclick="location.reload()">Try again</button><a class="btn" href="index-page.html">Open sprites</a></div></div></div></main>';
  }
}
document.addEventListener("DOMContentLoaded",safeStart);
