import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "./supabase-config.js";
const $=id=>document.getElementById(id);
const configured=SUPABASE_URL&&SUPABASE_ANON_KEY&&!SUPABASE_URL.includes("YOUR-PROJECT-REF")&&!SUPABASE_ANON_KEY.includes("YOUR_SUPABASE");
const supabase=configured?createClient(SUPABASE_URL,SUPABASE_ANON_KEY):null;
let mode="signup";
function msg(t,type="error"){const e=$(type==="success"?"authSuccess":"authError");if(!e)return;e.textContent=t;e.style.display="block";const o=$(type==="success"?"authError":"authSuccess");if(o)o.style.display="none"}
function clearMsg(){["authError","authSuccess"].forEach(id=>{$(id)&&($(id).style.display="none")})}
function localSession(name,provider){localStorage.ss_name=name||"Guest Trader";localStorage.ss_provider=provider||"Email";localStorage.ss_signed_in="1";setStatus(null,{name:localStorage.ss_name,provider:localStorage.ss_provider,local:true});msg(`Signed in locally as ${localStorage.ss_name}. This demo session works now; connect Supabase for shared real accounts.` ,"success")}
function setStatus(user,local){const signed=!!user||!!localStorage.ss_signed_in;const name=user?.user_metadata?.full_name||user?.user_metadata?.name||user?.email||localStorage.ss_name||"Guest Trader";const provider=local?.provider||user?.app_metadata?.provider||localStorage.ss_provider||"Email";if($("authStatus"))$("authStatus").innerHTML=signed?`<span class="pulseDot"></span> Signed in as <b>${name}</b> <span class="providerBadge ${provider.toLowerCase()}">${provider}</span>`:`<span class="pulseDot"></span> Not signed in.`;if($("logoutBtn"))$("logoutBtn").style.display=signed?"inline-block":"none";if($("statStatus"))$("statStatus").textContent=signed?"Signed in":"Guest";if($("accountTitle")&&signed)$("accountTitle").textContent="Welcome back, "+name+".";renderIdentity(name);}
function renderIdentity(name){if($("accountName"))$("accountName").textContent=name;if($("accountAvatar")){const ph=localStorage.ss_avatar;$("accountAvatar").innerHTML=ph?`<img class="profilePhoto" src="${ph}" alt="Profile picture">`:name[0].toUpperCase()}if($("profileAvatar")){const ph=localStorage.ss_avatar;$("profileAvatar").innerHTML=ph?`<img class="profilePhoto" src="${ph}" alt="Profile picture">`:name[0].toUpperCase()}}
function setMode(next){mode=next;clearMsg();if($("showSignup"))$("showSignup").classList.toggle("primary",next==="signup");if($("showLogin"))$("showLogin").classList.toggle("primary",next==="login");if($("signupBtn"))$("signupBtn").style.display=next==="signup"?"inline-block":"none";if($("loginBtn"))$("loginBtn").style.display=next==="login"?"inline-block":"none";if($("confirmWrap"))$("confirmWrap").style.display=next==="signup"?"block":"none"}
async function oauth(provider){clearMsg();if(!configured){const names={google:"Google Demo",discord:"Discord Demo",azure:"Microsoft Demo"};localSession((localStorage.ss_name&&localStorage.ss_name!=="Guest Trader"?localStorage.ss_name:names[provider]),provider==="azure"?"Microsoft":provider[0].toUpperCase()+provider.slice(1));return}const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo:window.location.origin+window.location.pathname}});if(error)msg(error.message)}
async function signup(){clearMsg();const email=$("email")?.value.trim(),pass=$("password")?.value||"",confirm=$("confirmPassword")?.value||"";if(!email||pass.length<6){msg("Enter a valid email and a password with at least 6 characters.");return}if(pass!==confirm){msg("Your passwords do not match.");return}if(!configured){const users=JSON.parse(localStorage.ss_users||"{}");users[email]=pass;localStorage.ss_users=JSON.stringify(users);localSession(email.split("@")[0]||"Sprite Trader","Email");setTimeout(()=>location.href="profile.html",450);return}const {data,error}=await supabase.auth.signUp({email,password:pass});if(error)msg(error.message);else{msg(data.session?"Account created and signed in.":"Account created. Check your email to confirm your address.","success");if(data.session){setStatus(data.user);setTimeout(()=>location.href="profile.html",450)}}}
async function signin(){clearMsg();const email=$("email")?.value.trim(),pass=$("password")?.value||"";if(!email||!pass){msg("Enter your email and password.");return}if(!configured){const known=localStorage.ss_users?JSON.parse(localStorage.ss_users):{};if(known[email]&&known[email]===pass){localSession(email.split("@")[0],"Email");setTimeout(()=>location.href="profile.html",450)}else if(!known[email]){known[email]=pass;localStorage.ss_users=JSON.stringify(known);localSession(email.split("@")[0],"Email")}else msg("That password is incorrect.");return}const {data,error}=await supabase.auth.signInWithPassword({email,password:pass});if(error)msg(error.message);else{msg("Signed in successfully.","success");setStatus(data.user)}}
async function logout(){if(configured&&supabase){const {error}=await supabase.auth.signOut();if(error)return msg(error.message)}localStorage.removeItem("ss_signed_in");localStorage.removeItem("ss_provider");setStatus(null,null);msg("You have been signed out.","success")}
function saveName(){const n=$("newName")?.value.trim()||"Guest Trader";localStorage.ss_name=n;setStatus(null,{name:n,provider:localStorage.ss_provider||"Email",local:true});msg("Profile name saved.","success")}
function handlePhoto(file){if(!file||!file.type.startsWith("image/")){msg("Please choose an image file.");return}if(file.size>2*1024*1024){msg("Please choose an image smaller than 2 MB.");return}const r=new FileReader();r.onload=()=>{localStorage.ss_avatar=r.result;renderIdentity(localStorage.ss_name||"Guest Trader");msg("Profile picture updated.","success")};r.readAsDataURL(file)}
$("googleBtn")?.addEventListener("click",()=>oauth("google"));$("discordBtn")?.addEventListener("click",()=>oauth("discord"));$("microsoftBtn")?.addEventListener("click",()=>oauth("azure"));$("showSignup")?.addEventListener("click",()=>setMode("signup"));$("showLogin")?.addEventListener("click",()=>setMode("login"));$("signupBtn")?.addEventListener("click",signup);$("loginBtn")?.addEventListener("click",signin);$("logoutBtn")?.addEventListener("click",logout);$("profilePhotoInput")?.addEventListener("change",e=>handlePhoto(e.target.files[0]));$("saveProfileName")?.addEventListener("click",saveName);
if(configured){supabase.auth.onAuthStateChange((_e,s)=>setStatus(s?.user));supabase.auth.getUser().then(({data})=>setStatus(data.user||null))}else{setStatus(null,null);if($("authStatus"))$("authStatus").innerHTML='<span class="pulseDot"></span> Local account mode — buttons work now.'}
setMode(new URLSearchParams(location.search).get("mode")==="login"?"login":"signup");