(function(){
function norm(s){return typeof s==='string'?{name:s,tier:'Base',level:1}:{name:s.name,tier:s.tier||'Base',level:Number(s.level||1)};}
function posts(){try{return JSON.parse(localStorage.getItem('spriteswap-trade-posts')||'[]')}catch(e){return[]}}
function savePosts(a){localStorage.setItem('spriteswap-trade-posts',JSON.stringify(a));window.dispatchEvent(new Event('spriteswap-posts-changed'))}
function cleanup(){var a=posts(),now=Date.now(),changed=false;a.forEach(function(x){if(!x.expiresAt)x.expiresAt=Number(x.createdAt||now)+172800000;if((x.status||'open')==='open'&&x.expiresAt<=now){x.status='expired';changed=true}});if(changed)savePosts(a);return a}
function duplicate(x){var a=(x.get||[]).map(norm).map(function(s){return s.name+'::'+s.tier}),b=(x.give||[]).map(norm).map(function(s){return s.name+'::'+s.tier});return a.some(function(id){return b.indexOf(id)>=0})}
function needMatch(x){var n=savedList('spriteswap-need');return(x.get||[]).map(norm).some(function(s){return n.indexOf(s.name+'::'+s.tier)>=0})}
function left(t){var m=Math.max(0,Number(t)-Date.now()),h=Math.floor(m/3600000),mi=Math.floor(m%3600000/60000);return h+'h '+mi+'m left'}
window.initTrades=function(){
 cleanup();
 function render(){
  var q=document.getElementById('postSearch').value.toLowerCase().trim(),side=document.getElementById('postSide').value,tier=document.getElementById('postTier').value,level=document.getElementById('postLevel').value,smart=document.getElementById('smartMatch').checked,sort=document.getElementById('postSort').value;
  var a=cleanup().filter(function(x){if((x.status||'open')!=='open'||duplicate(x))return false;var arr=[].concat(x.get||[],x.give||[]).map(norm),sideArr=side==='get'?x.get:side==='give'?x.give:arr,names=arr.map(function(s){return s.name+' '+s.tier}).join(' ').toLowerCase();return(!q||names.indexOf(q)>=0||String(x.trader||'').toLowerCase().indexOf(q)>=0||String(x.title||'').toLowerCase().indexOf(q)>=0)&&sideArr.length&&(tier==='all'||arr.some(function(s){return s.tier===tier}))&&(level==='all'||arr.some(function(s){return s.level>=Number(level)}))&&(!smart||needMatch(x))});
  a.sort(function(x,y){if(sort==='ending')return x.expiresAt-y.expiresAt;if(sort==='sprites')return((y.get||[]).length+(y.give||[]).length)-((x.get||[]).length+(x.give||[]).length);return Number(y.createdAt||0)-Number(x.createdAt||0)});
  layout('Trades','Trades','<main><section class="hero trades-hero"><div class="shell"><div class="kicker">TRADING BOARD</div><h1>Find your next<br><span style="color:var(--mint)">sprite swap.</span></h1><p>Listings expire after 48 hours. Click a trade for details, then accept to start a private chat.</p><div class="actions"><button class="btn primary" id="newTradePost">+ Post a trade</button><a class="btn" href="chat.html">Community chat</a></div></div></section><section class="section"><div class="shell"><div class="post-filters"><input id="postSearch" class="input" placeholder="Search trades…"><select id="postSide" class="select"><option value="all">All posts</option><option value="get">Looking for</option><option value="give">Offering</option></select><select id="postTier" class="select"><option value="all">Any variant</option>'+TIERS.map(function(t){return'<option>'+esc(t)+'</option>'}).join('')+'</select><select id="postLevel" class="select"><option value="all">Any level</option><option value="2">Level 2+</option><option value="3">Level 3+</option><option value="4">Level 4+</option><option value="5">Level 5</option></select><select id="postSort" class="select"><option value="newest">Newest</option><option value="ending">Ending soon</option><option value="sprites">Most sprites</option></select><label class="trade-filter-check"><input id="smartMatch" type="checkbox"> Show trades that give me something I need</label><button id="clearPostFilters" class="btn">Reset</button></div><div id="tradePostList" class="trade-post-list">'+(a.map(function(x){return'<article class="trade-post" data-post-view="'+esc(x.id)+'"><div class="trade-post-top"><div><span class="badge">OPEN</span><h3>'+esc(x.title||'Sprite trade')+'</h3><p class="muted">'+esc(x.trader||'SpriteSwap Trader')+' · '+left(x.expiresAt)+'</p></div><button class="btn primary">View trade</button></div><div class="post-columns"><div><div class="post-side-title get">YOU GET</div><div>'+x.get.map(function(s){s=norm(s);return'<span class="trade-chip">'+esc(s.name)+' · '+esc(s.tier)+' · L'+s.level+'</span>'}).join('')+'</div></div><div><div class="post-side-title give">YOU GIVE</div><div>'+x.give.map(function(s){s=norm(s);return'<span class="trade-chip">'+esc(s.name)+' · '+esc(s.tier)+' · L'+s.level+'</span>'}).join('')+'</div></div></div><p class="muted">'+esc(x.note||'Open to fair offers.')+'</p></article>'}).join('')||'<div class="notice empty-posts">No open trade posts.</div>')+'</div></div></section></main>');
  document.getElementById('newTradePost').onclick=openTradePostModal;['postSearch','postSide','postTier','postLevel','postSort','smartMatch'].forEach(function(id){document.getElementById(id).oninput=render;document.getElementById(id).onchange=render});document.getElementById('clearPostFilters').onclick=function(){document.getElementById('postSearch').value='';document.getElementById('postSide').value='all';document.getElementById('postTier').value='all';document.getElementById('postLevel').value='all';document.getElementById('postSort').value='newest';document.getElementById('smartMatch').checked=false;render()};document.querySelectorAll('[data-post-view]').forEach(function(el){el.onclick=function(){var x=posts().find(function(p){return p.id===el.getAttribute('data-post-view')});if(x)openTradeDetails(x)}})
 }
 render();
};
window.initPrivateTradeChat=function(){var id=decodeURIComponent((location.hash||'').replace('#trade-chat=','')),x=cleanup().find(function(p){return p.id===id});if(!x||x.status!=='negotiating'){location.hash='';return initTrades()}var me=String(profileData().name||'SpriteSwap Trader'),key='spriteswap-private-chat-'+id;function read(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return[]}}function render(){var msgs=read(),people=[String(x.trader||'Trader'),String(x.acceptedBy||me)],done=x.completedBy||[];layout('Private Trade','Trades','<main><section class="section"><div class="shell"><div class="kicker">PRIVATE TRADE</div><h1>'+esc(x.title||'Sprite trade')+'</h1><p class="muted">'+esc(people[0])+' ↔ '+esc(people[1])+'</p><div class="notice"><b>Completion:</b> '+done.length+'/'+people.length+' marked complete.</div><div class="chat-messages">'+(msgs.map(function(m){return'<div class="chat-msg"><div class="avatar">'+esc((m.name||'S')[0])+'</div><div class="chat-bubble"><b>'+esc(m.name)+'</b><div>'+esc(m.text)+'</div></div></div>'}).join('')||'<div class="notice">No messages yet.</div>')+'</div><div class="chat-compose"><input id="privateInput" class="input" placeholder="Talk about this trade…"><button id="privateSend" class="btn primary">Send</button></div><div class="actions"><button id="completeTrade" class="btn primary">Mark my side complete</button><button id="returnBoard" class="btn danger-btn">Return trade to board</button></div></div></section></main>');privateSend.onclick=function(){var t=privateInput.value.trim();if(!t)return;var a=read();a.push({name:me,text:t,createdAt:Date.now()});localStorage.setItem(key,JSON.stringify(a.slice(-200)));render()};privateInput.onkeydown=function(e){if(e.key==='Enter')privateSend.click()};completeTrade.onclick=function(){var a=posts(),p=a.find(function(z){return z.id===id});if(!p)return;p.completedBy=Array.from(new Set([].concat(p.completedBy||[],me)));if([String(p.trader||'Trader'),String(p.acceptedBy||me)].every(function(n){return p.completedBy.indexOf(n)>=0}))p.status='completed';savePosts(a);if(p.status==='completed'){var other=String(p.trader||'Trader')===me?String(p.acceptedBy||'Trader'):String(p.trader||'Trader');var rv=prompt('Rate this completed trade from 1 to 5');if(rv){var rr;try{rr=JSON.parse(localStorage.getItem('spriteswap-trade-reviews')||'[]')}catch(e){rr=[]}rr.push({tradeId:id,from:me,to:other,rating:Math.max(1,Math.min(5,Number(rv)||1)),createdAt:Date.now()});localStorage.setItem('spriteswap-trade-reviews',JSON.stringify(rr.slice(-500)))}}render()};returnBoard.onclick=function(){var a=posts(),p=a.find(function(z){return z.id===id});if(p){p.status='open';p.expiresAt=Date.now()+172800000;savePosts(a)}location.href='trades.html'}}render()};
window.initProfile=function(){var me=String(profileData().name||'SpriteSwap Trader'),done=cleanup().filter(function(x){return x.status==='completed'&&(x.trader===me||x.acceptedBy===me)}),rr;try{rr=JSON.parse(localStorage.getItem('spriteswap-trade-reviews')||'[]')}catch(e){rr=[]}layout('Profile','Profile','<main><section class="hero"><div class="shell"><div class="kicker">PROFILE</div><h1>'+esc(me)+'</h1><p>Collection, trading history and reputation.</p></div></section><section class="section"><div class="shell"><div class="stats"><div class="stat"><b>'+savedList('spriteswap-have').length+'</b><span>Have</span></div><div class="stat"><b>'+savedList('spriteswap-need').length+'</b><span>Need</span></div><div class="stat"><b>'+savedList('spriteswap-mastered').length+'</b><span>Mastered</span></div><div class="stat"><b>'+done.length+'</b><span>Completed trades</span></div></div><div class="hero-card"><h2>Trade history</h2>'+(done.map(function(x){return'<div class="row"><div class="grow"><b>'+esc(x.title||'Sprite trade')+'</b><div class="muted">'+esc(x.trader)+' ↔ '+esc(x.acceptedBy||'Trader')+'</div></div><span class="badge">COMPLETED</span></div>}).join('')||'<div class="notice">No completed trades yet.</div>')+'</div></div></section></main>');};
var oldSimple=window.initSimple;window.initSimple=function(){var p=location.pathname.split('/').pop()||'index.html';if(p==='profile.html')return initProfile();if(p==='new-this-week.html'){pageShell('New This Week','LATEST','New This Week','Released sprites live here; Upcoming is for unreleased watches.','<div class="grid">'+spriteCards(NEW.concat(['Pacman']),'Base')+'</div>');bindSpriteActions();return}oldSimple()};
})();