(function(){
function norm(s){return typeof s==='string'?{name:s,tier:'Base',level:1}:{name:String(s.name||''),tier:s.tier||'Base',level:Number(s.level||1)}}
function posts(){try{return JSON.parse(localStorage.getItem('spriteswap-trade-posts')||'[]')}catch(e){return[]}}
function savePosts(a){localStorage.setItem('spriteswap-trade-posts',JSON.stringify(a));window.dispatchEvent(new Event('spriteswap-posts-changed'))}
function reviewData(){try{return JSON.parse(localStorage.getItem('spriteswap-trade-reviews')||'[]')}catch(e){return[]}}
function me(){return String(profileData().name||'SpriteSwap Trader')}
function cleanup(){var a=posts(),now=Date.now(),changed=false;a.forEach(function(x){if(!x.createdAt)x.createdAt=now;if(!x.expiresAt)x.expiresAt=Number(x.createdAt)+172800000;if((x.status||'open')==='open'&&Number(x.expiresAt)<=now){x.status='expired';changed=true}});if(changed)savePosts(a);return a}
function sameSide(x){var g=(x.get||[]).map(norm).map(function(s){return s.name+'::'+s.tier}),o=(x.give||[]).map(norm).map(function(s){return s.name+'::'+s.tier});return g.some(function(v){return o.indexOf(v)>=0})}
function smart(x){var need=savedList('spriteswap-need');return (x.get||[]).map(norm).some(function(s){return need.indexOf(s.name+'::'+s.tier)>=0})}
function left(t){var m=Math.max(0,Number(t)-Date.now()),h=Math.floor(m/3600000),mi=Math.floor(m%3600000/60000);return h+'h '+mi+'m'}
function levelOptions(v){return [1,2,3,4,5].map(function(n){return '<option value="'+n+'"'+(Number(v||1)===n?' selected':'')+'>Level '+n+'</option>'}).join('')}
function picker(side,s){s=norm(s||{});return '<div class="picker-row"><select class="select pick-name">'+postSpriteOptions()+'</select><select class="select pick-tier">'+TIERS.map(function(t){return '<option'+(t===s.tier?' selected':'')+'>'+esc(t)+'</option>'}).join('')+'</select><select class="select pick-level">'+levelOptions(s.level)+'</select><button class="mini-btn remove-pick" type="button">×</button></div>'}
window.openTradePostModal=function(existing){
 var modal=document.createElement('div');modal.className='modal-backdrop';var p=existing||{};
 modal.innerHTML='<div class="modal wide-modal"><button class="modal-x">×</button><div class="kicker">TRADE POST</div><h2>'+esc(p.title||'Create a trade')+'</h2><label>Title<input id="tradeTitle" class="input" value="'+esc(p.title||'')+'" placeholder="What are you looking for?"></label><label>Note<textarea id="tradeNote" class="input" rows="3">'+esc(p.note||'')+'</textarea></label><div class="post-builder"><section><div class="post-side-title get">YOU GET</div><div id="getPickers">'+(p.get||[]).map(function(s){return picker('get',s)}).join('')+'</div><button id="addGet" class="btn" type="button">+ Add sprite</button></section><section><div class="post-side-title give">YOU GIVE</div><div id="givePickers">'+(p.give||[]).map(function(s){return picker('give',s)}).join('')+'</div><button id="addGive" class="btn" type="button">+ Add sprite</button></section></div><div class="actions"><button id="saveTrade" class="btn primary">Post trade</button></div></div>';
 document.body.appendChild(modal);modal.querySelector('.modal-x').onclick=function(){modal.remove()};
 function add(id,side){document.getElementById(id).insertAdjacentHTML('beforeend',picker(side,{}))}
 document.getElementById('addGet').onclick=function(){add('getPickers','get')};document.getElementById('addGive').onclick=function(){add('givePickers','give')};
 modal.addEventListener('click',function(e){if(e.target.classList.contains('remove-pick'))e.target.parentElement.remove()});
 document.getElementById('saveTrade').onclick=function(){
  function read(id){return Array.from(modal.querySelectorAll('#'+id+' .picker-row')).map(function(r){return{name:r.querySelector('.pick-name').value,tier:r.querySelector('.pick-tier').value,level:Number(r.querySelector('.pick-level').value||1)}})}
  var get=read('getPickers'),give=read('givePickers');if(!get.length||!give.length)return alert('Add at least one sprite on both sides.');
  var candidate={get:get,give:give};if(sameSide(candidate))return alert('The same sprite variant cannot be on both sides.');
  var a=cleanup(),o=Object.assign({},p);o.id=o.id||('trade-'+Date.now()+'-'+Math.random().toString(36).slice(2,8));o.title=document.getElementById('tradeTitle').value.trim()||'Sprite trade';o.note=document.getElementById('tradeNote').value.trim();o.get=get;o.give=give;o.trader=o.trader||me();o.createdAt=o.createdAt||Date.now();o.expiresAt=Date.now()+172800000;o.status='open';delete o.acceptedBy;delete o.acceptedAt;delete o.completedBy;
  var i=a.findIndex(function(x){return x.id===o.id});if(i<0)a.unshift(o);else a[i]=o;savePosts(a);modal.remove();
 };
};
function openTradeDetails(x){
 var modal=document.createElement("div");modal.className="modal-backdrop";
 var canAccept=(x.status||"open")==="open"&&String(x.trader||"")!==me()&&!sameSide(x);
 modal.innerHTML='<div class="modal wide-modal"><button class="modal-x">×</button><div class="kicker">TRADE DETAILS</div><h2>'+esc(x.title||"Sprite trade")+'</h2><p class="muted">'+esc(x.trader||"Trader")+' · expires in '+left(x.expiresAt)+'</p><div class="post-builder"><section><div class="post-side-title get">YOU GET</div>'+[].concat(x.get||[]).map(function(s){s=norm(s);return '<span class="trade-chip">'+esc(s.name)+' · '+esc(s.tier)+' · L'+s.level+'</span>';}).join('')+'</section><section><div class="post-side-title give">YOU GIVE</div>'+[].concat(x.give||[]).map(function(s){s=norm(s);return '<span class="trade-chip">'+esc(s.name)+' · '+esc(s.tier)+' · L'+s.level+'</span>';}).join('')+'</section></div><p class="muted">'+esc(x.note||"Open to fair offers.")+'</p><div class="actions">'+(canAccept?'<button id="acceptTrade" class="btn primary">Accept trade</button>':'<span class="badge">'+esc(x.status||"OPEN")+'</span>')+'<button id="closeTradeModal" class="btn">Close</button></div></div>';
 document.body.appendChild(modal);
 modal.querySelector(".modal-x").onclick=function(){modal.remove();};
 modal.querySelector("#closeTradeModal").onclick=function(){modal.remove();};
 if(canAccept)modal.querySelector("#acceptTrade").onclick=function(){
   var all=posts(),p=all.find(function(z){return z.id===x.id});if(!p)return;
   p.status="negotiating";p.acceptedBy=me();p.acceptedAt=Date.now();savePosts(all);modal.remove();
   location.href="trades.html#trade-chat="+encodeURIComponent(p.id);
 };
}
window.initTrades=function(){
 function render(){
  var q=(document.getElementById('postSearch').value||'').toLowerCase().trim(),side=document.getElementById('postSide').value,tier=document.getElementById('postTier').value,level=document.getElementById('postLevel').value,smartOnly=document.getElementById('smartMatch').checked,sort=document.getElementById('postSort').value;
  var a=cleanup().filter(function(x){
   if((x.status||'open')!=='open'||sameSide(x))return false;
   var arr=[].concat(x.get||[],x.give||[]).map(norm),sideArr=side==='get'?x.get:side==='give'?x.give:arr,names=arr.map(function(s){return s.name+' '+s.tier}).join(' ').toLowerCase();
   return sideArr.length&&(!q||names.indexOf(q)>=0||String(x.trader||'').toLowerCase().indexOf(q)>=0||String(x.title||'').toLowerCase().indexOf(q)>=0)&&(tier==='all'||arr.some(function(s){return s.tier===tier}))&&(level==='all'||arr.some(function(s){return s.level>=Number(level)}))&&(!smartOnly||smart(x));
  });
  a.sort(function(x,y){if(sort==='ending')return x.expiresAt-y.expiresAt;if(sort==='sprites')return ((y.get||[]).length+(y.give||[]).length)-((x.get||[]).length+(x.give||[]).length);return Number(y.createdAt)-Number(x.createdAt)});
  layout('Trades','Trades','<main><section class="hero trades-hero"><div class="shell"><div class="kicker">TRADING BOARD</div><h1>Find your next<br><span style="color:var(--mint)">sprite swap.</span></h1><p>Trade posts automatically close after 48 hours.</p><div class="actions"><button class="btn primary" id="newTradePost">+ Post a trade</button><a class="btn" href="chat.html">Community chat</a></div></div></section><section class="section"><div class="shell"><div class="post-filters"><input id="postSearch" class="input" placeholder="Search trades…"><select id="postSide" class="select"><option value="all">All posts</option><option value="get">Looking for</option><option value="give">Offering</option></select><select id="postTier" class="select"><option value="all">Any variant</option>'+TIERS.map(function(t){return '<option>'+esc(t)+'</option>'}).join('')+'</select><select id="postLevel" class="select"><option value="all">Any level</option><option value="2">Level 2+</option><option value="3">Level 3+</option><option value="4">Level 4+</option><option value="5">Level 5</option></select><select id="postSort" class="select"><option value="newest">Newest</option><option value="ending">Ending soon</option><option value="sprites">Most sprites</option></select><label class="trade-filter-check"><input id="smartMatch" type="checkbox"> Show trades that give me something I need</label><button id="clearPostFilters" class="btn">Reset</button></div><div id="tradePostList" class="trade-post-list">'+(a.map(function(x){return '<article class="trade-post" data-post-view="'+esc(x.id)+'"><div class="trade-post-top"><div><span class="badge">OPEN</span><h3>'+esc(x.title||'Sprite trade')+'</h3><p class="muted">'+esc(x.trader||'Trader')+' · '+left(x.expiresAt)+'</p></div><button class="btn primary">View trade</button></div><div class="post-columns"><div><div class="post-side-title get">YOU GET</div>'+x.get.map(function(s){s=norm(s);return '<span class="trade-chip">'+esc(s.name)+' · '+esc(s.tier)+' · L'+s.level+'</span>'}).join('')+'</div><div><div class="post-side-title give">YOU GIVE</div>'+x.give.map(function(s){s=norm(s);return '<span class="trade-chip">'+esc(s.name)+' · '+esc(s.tier)+' · L'+s.level+'</span>'}).join('')+'</div></div><p class="muted">'+esc(x.note||'Open to fair offers.')+'</p></article>'}).join('')||'<div class="notice empty-posts"><b>No open trade posts.</b></div>')+'</div></div></section></main>');
  document.getElementById('newTradePost').onclick=function(){openTradePostModal()};
  ['postSearch','postSide','postTier','postLevel','postSort','smartMatch'].forEach(function(id){document.getElementById(id).oninput=render;document.getElementById(id).onchange=render});
  document.getElementById('clearPostFilters').onclick=function(){document.getElementById('postSearch').value='';document.getElementById('postSide').value='all';document.getElementById('postTier').value='all';document.getElementById('postLevel').value='all';document.getElementById('postSort').value='newest';document.getElementById('smartMatch').checked=false;render()};
  document.querySelectorAll('[data-post-view]').forEach(function(el){el.onclick=function(){var x=posts().find(function(p){return p.id===el.getAttribute('data-post-view')});if(x)openTradeDetails(x)}});
 }
 render();
};
window.initPrivateTradeChat=function(){
 var id=decodeURIComponent((location.hash||'').replace('#trade-chat=','')),x=cleanup().find(function(p){return p.id===id});if(!x||x.status!=='negotiating'){location.hash='';return initTrades()}
 var personA=String(x.trader||'Trader'),personB=String(x.acceptedBy||me()),user=me(),key='spriteswap-private-chat-'+id;
 function read(){try{return JSON.parse(localStorage.getItem(key)||'[]')}catch(e){return[]}}
 function render(){var done=x.completedBy||[],mine=done.indexOf(user)>=0,avg=done.length+'/'+[personA,personB].length;layout('Private Trade','Trades','<main><section class="section"><div class="shell"><div class="kicker">PRIVATE TRADE</div><h1>'+esc(x.title||'Sprite trade')+'</h1><p class="muted">'+esc(personA)+' ↔ '+esc(personB)+'</p><div class="notice"><b>Completion:</b> '+avg+' marked complete.</div><div class="chat-messages">'+read().map(function(m){return '<div class="chat-msg"><div class="avatar">'+esc((m.name||'S')[0])+'</div><div class="chat-bubble"><b>'+esc(m.name)+'</b><div>'+esc(m.text)+'</div></div></div>'}).join('')||'<div class="notice">No messages yet.</div>'+'</div><div class="chat-compose"><input id="privateInput" class="input" placeholder="Talk about this trade…"><button id="privateSend" class="btn primary">Send</button></div><div class="actions"><button id="completeTrade" class="btn primary"'+(mine?' disabled':'')+'>'+(mine?'✓ My side complete':'Mark my side complete')+'</button><button id="returnBoard" class="btn danger-btn">Return trade to board</button></div></div></section></main>');
  document.getElementById('privateSend').onclick=function(){var t=document.getElementById('privateInput').value.trim();if(!t)return;if(typeof moderateText==='function'){var mod=moderateText(t);if(!mod.ok){alert(mod.reason);return}}var a=read();a.push({name:user,text:t,createdAt:Date.now()});localStorage.setItem(key,JSON.stringify(a.slice(-200)));render()};
  document.getElementById('privateInput').onkeydown=function(e){if(e.key==='Enter')document.getElementById('privateSend').click()};
  document.getElementById('completeTrade').onclick=function(){var a=posts(),p=a.find(function(z){return z.id===id});if(!p)return;p.completedBy=Array.from(new Set([].concat(p.completedBy||[],user)));if([personA,personB].every(function(n){return p.completedBy.indexOf(n)>=0}))p.status='completed';savePosts(a);x=p;if(p.status==='completed'){var other=personA===user?personB:personA;var rv=prompt('Rate '+other+' from 1 to 5');if(rv){var rr=reviewData();rr.push({tradeId:id,from:user,to:other,rating:Math.max(1,Math.min(5,Number(rv)||1)),createdAt:Date.now()});localStorage.setItem('spriteswap-trade-reviews',JSON.stringify(rr.slice(-500)))}}render()};
  document.getElementById('returnBoard').onclick=function(){var a=posts(),p=a.find(function(z){return z.id===id});if(p){p.status='open';p.expiresAt=Date.now()+172800000;savePosts(a)}location.href='trades.html'};
 }
 render();
};
window.initProfile=function(){
 var user=me(),done=cleanup().filter(function(x){return x.status==='completed'&&(x.trader===user||x.acceptedBy===user)}),rr=reviewData(),incoming=rr.filter(function(r){return r.to===user}),avg=incoming.length?(incoming.reduce(function(s,r){return s+Number(r.rating||0)},0)/incoming.length).toFixed(1):'—';
 layout('Profile','Profile','<main><section class="hero"><div class="shell"><div class="kicker">PROFILE</div><h1>'+esc(user)+'</h1><p>Collection, trading history and trader reputation.</p></div></section><section class="section"><div class="shell"><div class="stats"><div class="stat"><b>'+savedList('spriteswap-have').length+'</b><span>Have</span></div><div class="stat"><b>'+savedList('spriteswap-need').length+'</b><span>Need</span></div><div class="stat"><b>'+savedList('spriteswap-mastered').length+'</b><span>Mastered</span></div><div class="stat"><b>'+done.length+'</b><span>Completed trades</span></div><div class="stat"><b>'+avg+'</b><span>Trader rating</span></div></div><div class="hero-card"><h2>Trader reviews</h2>'+(incoming.map(function(r){return '<div class="row"><div class="grow"><b>'+esc(r.from)+'</b><div class="muted">Completed trade</div></div><strong>'+esc(r.rating)+'/5</strong></div>'}).join('')||'<div class="notice">No reviews yet.</div>')+'</div><div class="hero-card"><h2>Trade history</h2>'+(done.map(function(x){return '<div class="row"><div class="grow"><b>'+esc(x.title||'Sprite trade')+'</b><div class="muted">'+esc(x.trader)+' ↔ '+esc(x.acceptedBy||'Trader')+'</div></div><span class="badge">COMPLETED</span></div>'}).join('')||'<div class="notice">No completed trades yet.</div>')+'</div></div></section></main>');
};
var oldSimple=window.initSimple;window.initSimple=function(){var p=location.pathname.split('/').pop()||'index.html';if((location.hash||"").indexOf("#trade-chat=")===0)return initPrivateTradeChat();if(p==='profile.html')return initProfile();if(p==='new-this-week.html'){var released=NEW.filter(function(n){return spriteSeason(n)===CURRENT_SEASON});pageShell('New This Week','LATEST','New This Week','Released sprites live here; Upcoming is for unreleased watches.','<div class="grid">'+spriteCards(released,'Base')+'</div>');bindSpriteActions();return}oldSimple()};
})();